using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using Microsoft.Xna.Framework;

namespace tsorcRevamp.Utilities
{
    public class WikiExporterCommand : ModCommand
    {
        public override CommandType Type => CommandType.Chat;

        public override string Command => "exportwikidata";

        public override string Description => "Exports item and NPC stats and XML import files for the wiki.gg database";

        public override void Action(CommandCaller caller, string input, string[] args)
        {
            try
            {
                string savePath = Main.SavePath;
                string workspacePath = Path.Combine(savePath, "ModSources", "tsorcRevamp", "Wiki");
                bool workspaceExists = Directory.Exists(workspacePath);

                string itemsFile = workspaceExists 
                    ? Path.Combine(workspacePath, "items_data.lua") 
                    : Path.Combine(savePath, "tsorc_items_data.lua");

                string npcsFile = workspaceExists 
                    ? Path.Combine(workspacePath, "npcs_data.lua") 
                    : Path.Combine(savePath, "tsorc_npcs_data.lua");

                string xmlFile = workspaceExists 
                    ? Path.Combine(workspacePath, "wiki_pages_import.xml") 
                    : Path.Combine(savePath, "tsorc_wiki_pages_import.xml");

                // Export Items Database
                ExportItems(itemsFile);

                // Export NPCs Database
                ExportNPCs(npcsFile);

                // Export XML Pages Import File
                ExportPagesXml(xmlFile);

                string msg = $"Success! Data exported to:\n- {itemsFile}\n- {npcsFile}\n- {xmlFile}";
                caller.Reply(msg, Color.Lime);
            }
            catch (Exception ex)
            {
                caller.Reply($"Export failed: {ex.Message}\n{ex.StackTrace}", Color.Red);
            }
        }

        private void ExportItems(string filePath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- This file is auto-generated by the /exportwikidata command. Do not edit by hand.");
            sb.AppendLine("return {");

            foreach (var modItem in ModContent.GetContent<ModItem>())
            {
                if (modItem.Mod != Mod) continue;

                Item item = ContentSamples.ItemsByType[modItem.Type];
                string displayName = item.Name;
                if (string.IsNullOrEmpty(displayName)) displayName = modItem.Name;

                string escapedDisplayName = EscapeLua(displayName);
                string escapedInternalName = EscapeLua(modItem.Name);
                string itemType = GetItemType(item);
                string rarity = GetRarityName(item.rare);
                string tooltip = GetTooltipText(item);

                sb.AppendLine($"    [\"{escapedDisplayName}\"] = {{");
                sb.AppendLine($"        name = \"{escapedDisplayName}\",");
                sb.AppendLine($"        internalName = \"{escapedInternalName}\",");
                sb.AppendLine($"        type = \"{itemType}\",");
                sb.AppendLine($"        damage = {item.damage},");
                sb.AppendLine($"        defense = {item.defense},");
                sb.AppendLine($"        useTime = {item.useTime},");
                sb.AppendLine($"        maxStack = {item.maxStack},");
                sb.AppendLine($"        value = {item.value},");
                sb.AppendLine($"        rare = \"{rarity}\",");
                sb.AppendLine($"        tooltip = \"{EscapeLua(tooltip)}\"");
                sb.AppendLine("    },");
            }

            sb.AppendLine("}");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
        }

        private void ExportNPCs(string filePath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- This file is auto-generated by the /exportwikidata command. Do not edit by hand.");
            sb.AppendLine("return {");

            foreach (var modNPC in ModContent.GetContent<ModNPC>())
            {
                if (modNPC.Mod != Mod) continue;

                NPC npc = ContentSamples.NpcsByNetId[modNPC.Type];
                string displayName = Lang.GetNPCNameValue(npc.type);
                if (string.IsNullOrEmpty(displayName)) displayName = modNPC.Name;

                string escapedDisplayName = EscapeLua(displayName);
                string escapedInternalName = EscapeLua(modNPC.Name);
                
                string category = npc.friendly ? (npc.townNPC ? "Town NPC" : "Friendly NPC") : (npc.boss ? "Boss" : "Enemy");
                float kbResist = 1f - npc.knockBackResist;

                sb.AppendLine($"    [\"{escapedDisplayName}\"] = {{");
                sb.AppendLine($"        name = \"{escapedDisplayName}\",");
                sb.AppendLine($"        internalName = \"{escapedInternalName}\",");
                sb.AppendLine($"        category = \"{category}\",");
                sb.AppendLine($"        lifeMax = {npc.lifeMax},");
                sb.AppendLine($"        defense = {npc.defense},");
                sb.AppendLine($"        damage = {npc.damage},");
                sb.AppendLine($"        knockbackResist = {kbResist:F2},");
                sb.AppendLine($"        value = {npc.value},");
                sb.AppendLine($"        boss = {(npc.boss ? "true" : "false")},");
                sb.AppendLine($"        townNPC = {(npc.townNPC ? "true" : "false")}");
                sb.AppendLine("    },");
            }

            sb.AppendLine("}");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
        }

        private void ExportPagesXml(string filePath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            sb.AppendLine("<mediawiki xmlns=\"http://www.mediawiki.org/xml/export-0.10/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.mediawiki.org/xml/export-0.10/ http://www.mediawiki.org/xml/export-0.10.xsd\" version=\"0.10\" xml:lang=\"en\">");

            // 1. Generate pages for all custom items
            foreach (var modItem in ModContent.GetContent<ModItem>())
            {
                if (modItem.Mod != Mod) continue;

                Item item = ContentSamples.ItemsByType[modItem.Type];
                string displayName = item.Name;
                if (string.IsNullOrEmpty(displayName)) displayName = modItem.Name;

                string pageTitle = $"The Story of Red Cloud/{displayName}";
                string itemType = GetItemType(item);

                // Build page contents
                var pageContent = new StringBuilder();
                pageContent.AppendLine("{{The Story of Red Cloud/Infobox item}}");
                pageContent.AppendLine("");
                pageContent.AppendLine($"The '''{displayName}''' is a modded [[{itemType}]] added by [[The Story of Red Cloud]].");
                pageContent.AppendLine("");
                pageContent.AppendLine("== Crafting ==");
                pageContent.AppendLine("=== Recipes ===");
                pageContent.AppendLine($"{{{{recipes|{displayName}}}}}");
                pageContent.AppendLine("");
                
                if (itemType == "Weapon" || itemType == "Armor" || itemType == "Accessory")
                {
                    pageContent.AppendLine("{{The Story of Red Cloud/Navbox equipment}}");
                }

                WriteXmlPage(sb, pageTitle, pageContent.ToString());
            }

            // 2. Generate pages for all custom NPCs
            foreach (var modNPC in ModContent.GetContent<ModNPC>())
            {
                if (modNPC.Mod != Mod) continue;

                NPC npc = ContentSamples.NpcsByNetId[modNPC.Type];
                string displayName = Lang.GetNPCNameValue(npc.type);
                if (string.IsNullOrEmpty(displayName)) displayName = modNPC.Name;

                string pageTitle = $"The Story of Red Cloud/{displayName}";
                string category = npc.friendly ? (npc.townNPC ? "Town NPC" : "Friendly NPC") : (npc.boss ? "Boss" : "Enemy");

                var pageContent = new StringBuilder();
                pageContent.AppendLine("{{The Story of Red Cloud/NPC infobox}}");
                pageContent.AppendLine("");
                pageContent.AppendLine($"The '''{displayName}''' is a modded [[{category}]] added by [[The Story of Red Cloud]].");
                pageContent.AppendLine("");
                pageContent.AppendLine("== Drops ==");
                pageContent.AppendLine("=== Loot ===");
                pageContent.AppendLine($"{{{{drops|{displayName}}}}}");

                WriteXmlPage(sb, pageTitle, pageContent.ToString());
            }

            sb.AppendLine("</mediawiki>");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
        }

        private void WriteXmlPage(StringBuilder sb, string title, string text)
        {
            sb.AppendLine("  <page>");
            sb.AppendLine($"    <title>{EscapeXml(title)}</title>");
            sb.AppendLine("    <ns>0</ns>");
            sb.AppendLine("    <revision>");
            sb.AppendLine("      <model>wikitext</model>");
            sb.AppendLine("      <format>text/x-wiki</format>");
            sb.AppendLine($"      <text xml:space=\"preserve\">{EscapeXml(text)}</text>");
            sb.AppendLine("    </revision>");
            sb.AppendLine("  </page>");
        }

        private string GetItemType(Item item)
        {
            if (item.accessory) return "Accessory";
            if (item.damage > 0) return "Weapon";
            if (item.headSlot != -1 || item.bodySlot != -1 || item.legSlot != -1) return "Armor";
            if (item.pick > 0 || item.axe > 0 || item.hammer > 0) return "Tool";
            if (item.ammo != AmmoID.None) return "Ammo";
            if (item.consumable && (item.buffType > 0 || item.healLife > 0 || item.healMana > 0)) return "Potion";
            if (item.createTile >= 0 || item.createWall >= 0) return "Tile";
            if (item.material) return "Crafting material";
            return "Miscellaneous";
        }

        private string GetRarityName(int rare)
        {
            if (rare >= 12 || rare < -11)
            {
                var customRarity = RarityLoader.GetRarity(rare);
                if (customRarity != null)
                {
                    return customRarity.Name;
                }
            }

            switch (rare)
            {
                case -11: return "Amber";
                case -1: return "Gray";
                case 0: return "White";
                case 1: return "Blue";
                case 2: return "Green";
                case 3: return "Orange";
                case 4: return "LightRed";
                case 5: return "Pink";
                case 6: return "LightPurple";
                case 7: return "Lime";
                case 8: return "Yellow";
                case 9: return "Cyan";
                case 10: return "Red";
                case 11: return "Purple";
                case 12: return "Rainbow";
                case 13: return "FieryRed";
                default: return "White";
            }
        }

        private string GetTooltipText(Item item)
        {
            var tooltip = Lang.GetTooltip(item.type);
            if (tooltip == null) return "";

            var lines = new List<string>();
            for (int i = 0; i < tooltip.Lines; i++)
            {
                string line = tooltip.GetLine(i);
                if (!string.IsNullOrEmpty(line))
                {
                    lines.Add(line);
                }
            }
            return string.Join("\n", lines);
        }

        private string EscapeLua(string str)
        {
            if (string.IsNullOrEmpty(str)) return "";
            return str
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "");
        }

        private string EscapeXml(string str)
        {
            if (string.IsNullOrEmpty(str)) return "";
            return str
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("'", "&apos;");
        }
    }
}
