-- This file is auto-generated by the /exportwikidata command. Do not edit by hand.
return {
    ["ArmorSet_AbyssalNinjaMask"] = {
        name = "Abyssal Ninja Armor",
        wikiName = "Abyssal Ninja Armor",
        heads = {
            "AbyssalNinjaMask",
        },
        bodies = {
            "AbyssalNinjaTop",
        },
        legs = {
            "AbyssalNinjaBottoms",
        },
    },
    ["ArmorSet_AncientGoldenArmor"] = {
        name = "Ancient Golden Armor",
        wikiName = "Ancient Golden Armor",
        heads = {
            "AncientGoldenHelmet",
        },
        bodies = {
            "AncientGoldenArmor",
        },
        legs = {
            "AncientGoldenGreaves",
        },
    },
    ["ArmorSet_AncientMagicPlateArmor"] = {
        name = "Ancient Magic Armor",
        wikiName = "Ancient Magic Armor",
        heads = {
            "AncientHornedHelmet",
        },
        bodies = {
            "AncientMagicPlateArmor",
        },
        legs = {
            "AncientMagicPlateGreaves",
        },
    },
    ["ArmorSet_AnkorWatChestplate"] = {
        name = "Ankor Wat Armor",
        wikiName = "Ankor Wat Armor",
        heads = {
            "AnkorWatHelmet",
        },
        bodies = {
            "AnkorWatChestplate",
        },
        legs = {
            "AnkorWatLeggings",
        },
    },
    ["ArmorSet_ArcherOfLumeliaShirt"] = {
        name = "Archer of Lumelia Armor",
        wikiName = "Archer of Lumelia Armor",
        heads = {
            "ArcherOfLumeliaHairStyle",
        },
        bodies = {
            "ArcherOfLumeliaShirt",
        },
        legs = {
            "ArcherOfLumeliaPants",
        },
    },
    ["ArmorSet_ArtoriasArmor"] = {
        name = "Artorias Armor",
        wikiName = "Artorias Armor",
        heads = {
            "ArtoriasHelmet",
        },
        bodies = {
            "ArtoriasArmor",
        },
        legs = {
            "ArtoriasGreaves",
        },
    },
    ["ArmorSet_BlackBeltGiTop"] = {
        name = "Black Belt Gi Armor",
        wikiName = "Black Belt Gi Armor",
        heads = {
            "BlackBeltHairStyle",
        },
        bodies = {
            "BlackBeltGiTop",
        },
        legs = {
            "BlackBeltGiPants",
        },
    },
    ["ArmorSet_BlueHerosHat"] = {
        name = "Blue Hero's Armor",
        wikiName = "Blue Hero's Armor",
        heads = {
            "BlueHerosHat",
        },
        bodies = {
            "BlueHerosShirt",
        },
        legs = {
            "BlueHerosPants",
        },
    },
    ["ArmorSet_BrassArmor"] = {
        name = "Brass Armor",
        wikiName = "Brass Armor",
        heads = {
            "BrassHelmet",
        },
        bodies = {
            "BrassArmor",
        },
        legs = {
            "BrassGreaves",
        },
    },
    ["ArmorSet_CrystalEnchantedHelmet"] = {
        name = "Crystal Enchanted Armor",
        wikiName = "Crystal Enchanted Armor",
        heads = {
            "CrystalEnchantedHelmet",
        },
        bodies = {
            "CrystalArmor",
        },
        legs = {
            "CrystalGreaves",
        },
    },
    ["ArmorSet_CrystalSightedHelmet"] = {
        name = "Crystal Sighted Armor",
        wikiName = "Crystal Sighted Armor",
        heads = {
            "CrystalSightedHelmet",
        },
        bodies = {
            "CrystalArmor",
        },
        legs = {
            "CrystalGreaves",
        },
    },
    ["ArmorSet_DarkKnightArmor"] = {
        name = "Dark Knight Armor",
        wikiName = "Dark Knight Armor",
        heads = {
            "DarkKnightHelmet",
        },
        bodies = {
            "DarkKnightArmor",
        },
        legs = {
            "DarkKnightGreaves",
        },
    },
    ["ArmorSet_AncientDemonArmor"] = {
        name = "Defiled Demon Armor",
        wikiName = "Defiled Demon Armor",
        heads = {
            "AncientDemonHelmet",
        },
        bodies = {
            "AncientDemonArmor",
        },
        legs = {
            "AncientDemonGreaves",
        },
    },
    ["ArmorSet_DragonScaleMail"] = {
        name = "Dragon Scale Armor",
        wikiName = "Dragon Scale Armor",
        heads = {
            "DragonScaleHelmet",
        },
        bodies = {
            "DragonScaleMail",
        },
        legs = {
            "DragonScaleGreaves",
        },
    },
    ["ArmorSet_DragoonArmor"] = {
        name = "Dragoon Armor",
        wikiName = "Dragoon Armor",
        heads = {
            "DragoonHelmet",
            "DragoonHelmet2",
        },
        bodies = {
            "DragoonArmor",
            "DragoonArmor2",
        },
        legs = {
            "DragoonGreaves",
            "DragoonGreaves2",
        },
    },
    ["ArmorSet_DwarvenCrusaderHelmet"] = {
        name = "Dwarven Crusader Armor",
        wikiName = "Dwarven Crusader Armor",
        heads = {
            "DwarvenCrusaderHelmet",
        },
        bodies = {
            "DwarvenArmor",
        },
        legs = {
            "DwarvenGreaves",
        },
    },
    ["ArmorSet_DwarvenKnightHelmet"] = {
        name = "Dwarven Knight Armor",
        wikiName = "Dwarven Knight Armor",
        heads = {
            "DwarvenKnightHelmet",
        },
        bodies = {
            "DwarvenArmor",
        },
        legs = {
            "DwarvenGreaves",
        },
    },
    ["ArmorSet_FighterBreastplate"] = {
        name = "Fighter Armor",
        wikiName = "Fighter Armor",
        heads = {
            "FighterHairStyle",
        },
        bodies = {
            "FighterBreastplate",
        },
        legs = {
            "FighterGreaves",
        },
    },
    ["ArmorSet_GenjiArmor"] = {
        name = "Genji Armor",
        wikiName = "Genji Armor",
        heads = {
            "GenjiHelmet",
        },
        bodies = {
            "GenjiArmor",
        },
        legs = {
            "GenjiGreaves",
        },
    },
    ["ArmorSet_HollowSoldierBreastplate"] = {
        name = "Hollow Soldier Armor",
        wikiName = "Hollow Soldier Armor",
        heads = {
            "HollowSoldierHelmet",
        },
        bodies = {
            "HollowSoldierBreastplate",
        },
        legs = {
            "HollowSoldierWaistcloth",
        },
    },
    ["ArmorSet_KrakenCarcass"] = {
        name = "Kraken Carcass Armor Set",
        wikiName = "Kraken Carcass Armor Set",
        heads = {
            "KrakenHead",
        },
        bodies = {
            "KrakenCarcass",
        },
        legs = {
            "KrakenLegs",
        },
    },
    ["ArmorSet_LeatherArmor"] = {
        name = "Leather Armor",
        wikiName = "Leather Armor",
        heads = {
            "LeatherHelmet",
        },
        bodies = {
            "LeatherArmor",
        },
        legs = {
            "LeatherGreaves",
        },
    },
    ["ArmorSet_Linklight2sHat"] = {
        name = "Linklight2s Armor",
        wikiName = "Linklight2s Armor",
        heads = {
            "Linklight2sHat",
        },
        bodies = {
            "Linklight2sShirt",
        },
        legs = {
            "Linklight2sPants",
        },
    },
    ["ArmorSet_MagmaBreastplate"] = {
        name = "Magma Armor",
        wikiName = "Magma Armor",
        heads = {
            "MagmaHelmet",
        },
        bodies = {
            "MagmaBreastplate",
        },
        legs = {
            "MagmaGreaves",
        },
    },
    ["ArmorSet_MimeticSuit"] = {
        name = "Mimetic Suit Armor Set",
        wikiName = "Mimetic Suit Armor Set",
        heads = {
            "MimeticHat",
        },
        bodies = {
            "MimeticSuit",
        },
        legs = {
            "MimeticPants",
        },
    },
    ["ArmorSet_MirkwoodElvenLeatherArmor"] = {
        name = "Mirkwood Elven Leather Armor",
        wikiName = "Mirkwood Elven Leather Armor",
        heads = {
            "MirkwoodElvenBlondeHairStyle",
        },
        bodies = {
            "MirkwoodElvenLeatherArmor",
        },
        legs = {
            "MirkwoodElvenLeggings",
        },
    },
    ["ArmorSet_NecromancersShirt"] = {
        name = "Necromancers Armor",
        wikiName = "Necromancers Armor",
        heads = {
            "NecromancersSkullmask",
        },
        bodies = {
            "NecromancersShirt",
        },
        legs = {
            "NecromancersPants",
        },
    },
    ["ArmorSet_OldChainArmor"] = {
        name = "Old Chain Armor",
        wikiName = "Old Chain Armor",
        heads = {
            "OldChainCoif",
        },
        bodies = {
            "OldChainArmor",
        },
        legs = {
            "OldChainGreaves",
        },
    },
    ["ArmorSet_PortlyPlateChestplate"] = {
        name = "Portly Plate Armor",
        wikiName = "Portly Plate Armor",
        heads = {
            "PortlyPlateHelmet",
        },
        bodies = {
            "PortlyPlateChestplate",
        },
        legs = {
            "PortlyPlateGreaves",
        },
    },
    ["ArmorSet_RTQ2Chestplate"] = {
        name = "RTQ2 Armor",
        wikiName = "RTQ2 Armor",
        heads = {
            "RTQ2Helmet",
        },
        bodies = {
            "RTQ2Chestplate",
        },
        legs = {
            "RTQ2Leggings",
        },
    },
    ["ArmorSet_RedClothTunic"] = {
        name = "Red Cloth Armor",
        wikiName = "Red Cloth Armor",
        heads = {
            "RedClothHat",
        },
        bodies = {
            "RedClothTunic",
        },
        legs = {
            "RedClothPants",
        },
    },
    ["ArmorSet_RedHerosHat"] = {
        name = "Red Hero's Armor",
        wikiName = "Red Hero's Armor",
        heads = {
            "RedHerosHat",
        },
        bodies = {
            "RedHerosShirt",
        },
        legs = {
            "RedHerosPants",
        },
    },
    ["ArmorSet_ShadowCloakPlateMail"] = {
        name = "Shadow Cloak Plate Armor",
        wikiName = "Shadow Cloak Plate Armor",
        heads = {
            "ShadowCloakPlateHelm",
        },
        bodies = {
            "ShadowCloakPlateMail",
        },
        legs = {
            "ShadowCloakGreaves",
        },
    },
    ["ArmorSet_ShadowNinjaMask"] = {
        name = "Shadow Ninja Armor",
        wikiName = "Shadow Ninja Armor",
        heads = {
            "ShadowNinjaMask",
        },
        bodies = {
            "ShadowNinjaTop",
        },
        legs = {
            "ShadowNinjaBottoms",
        },
    },
    ["ArmorSet_ShamanCloak"] = {
        name = "Shaman Armor",
        wikiName = "Shaman Armor",
        heads = {
            "ShamanHood",
            "ShamanMask",
        },
        bodies = {
            "ShamanCloak",
        },
        legs = {
            "ShamanPants",
        },
    },
    ["ArmorSet_ShellHelmet"] = {
        name = "Shell Armor",
        wikiName = "Shell Armor",
        heads = {
            "ShellHelmet",
        },
        bodies = {
            "ShellArmor",
        },
        legs = {
            "ShellGreaves",
        },
    },
    ["ArmorSet_SmoughArmor"] = {
        name = "Smough's Armor",
        wikiName = "Smough's Armor",
        heads = {
            "SmoughHelmet",
        },
        bodies = {
            "SmoughArmor",
        },
        legs = {
            "SmoughGreaves",
        },
    },
    ["ArmorSet_SnipedStrangerHat"] = {
        name = "Sniped Stranger Armor",
        wikiName = "Sniped Stranger Armor",
        heads = {
            "SnipedStrangerHat",
        },
        bodies = {
            "SnarbolaxArmor",
        },
        legs = {
            "SnarbolaxGreaves",
        },
    },
    ["ArmorSet_StuddedLeatherArmor"] = {
        name = "Studded Leather Armor",
        wikiName = "Studded Leather Armor",
        heads = {
            "StuddedLeatherHelmet",
        },
        bodies = {
            "StuddedLeatherArmor",
        },
        legs = {
            "StuddedLeatherGreaves",
        },
    },
    ["ArmorSet_DragoonHelmet2"] = {
        name = "Supreme Dragoon Armor",
        wikiName = "Supreme Dragoon Armor",
        heads = {
            "DragoonHelmet2",
        },
        bodies = {
            "DragoonArmor2",
        },
        legs = {
            "DragoonGreaves2",
        },
    },
    ["ArmorSet_TarantulaHelmet"] = {
        name = "Tarantula Armor",
        wikiName = "Tarantula Armor",
        heads = {
            "TarantulaHelmet",
            "TarantulaMask",
        },
        bodies = {
            "TarantulaCarapace",
        },
        legs = {
            "TarantulaLegs",
        },
    },
    ["ArmorSet_TheUnknowable"] = {
        name = "The Unknowable Armor Set",
        wikiName = "The Unknowable Armor Set",
        heads = {
            "TheUnknowable",
        },
        bodies = {
            "TheUnforseeable",
        },
        legs = {
            "TheUntouchable",
        },
    },
    ["ArmorSet_TriceratopsBody"] = {
        name = "Triceratops Body Armor Set",
        wikiName = "Triceratops Body Armor Set",
        heads = {
            "TriceratopsHead",
        },
        bodies = {
            "TriceratopsBody",
        },
        legs = {
            "TriceratopsLegs",
        },
    },
    ["ArmorSet_WaspArmor"] = {
        name = "Wasp Armor",
        wikiName = "Wasp Armor",
        heads = {
            "WaspHelmet",
        },
        bodies = {
            "WaspArmor",
        },
        legs = {
            "WaspGreaves",
        },
    },
    ["ArmorSet_WitchkingRobe"] = {
        name = "Witchking Armor",
        wikiName = "Witchking Armor",
        heads = {
            "WitchkingHelmet",
        },
        bodies = {
            "WitchkingRobe",
        },
        legs = {
            "WitchkingPants",
        },
    },
}
